kind = "web"
previewPath = "/"
title = "Hochstapler Burger"
version = "1.0.0"
id = "artifacts/hochstapler-burger"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 8082

[services.env]
PORT = "8082"
BASE_PATH = "/"

[services.development]
run = "pnpm --filter @workspace/hochstapler-burger run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hochstapler-burger", "run", "build" ]
publicDir = "artifacts/hochstapler-burger/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
